install.packages('foreign')
install.packages('reshape')
install.packages('plyr')
install.packages('ggplot2')
install.packages('testthat')
install.packages('yaml')
install.packages('ProjectTemplate')
install.packages('SortableHTMLTables')
